### PR TITLE
[checkbox]: adds optional selected options

### PR DESCRIPTION
**Pull request by blackjid**
Hey @arlimus I added an option to the checkbox to start with some options already selected.

I'd appreciate if you can merge it if you like it.

thks..

### CODE REVIEW

**Comment by arlimus** [comment]
@blackjid Great addition, thank you again :)

Could you maybe change the syntax to be:
```
Ask.checkbox "Enter list...", list, default: [true, false, false]
```

This way it wouldn't collide with the way it's used in eg input and confirm. It should also fix the tests and leave it compatible with earlier syntax. What do you think?

**Comment by arlimus** [comment]
Awesome, thank you @blackjid !

(No worries about travis rbx-2.1, i'll update and remove next; everything else runs great)

**Comment by blackjid** [comment]
hey thanks!, that was fast... :)
You were right, much better syntax now, and it's also consistent with the input and confirm defaults.

I totally forgot about the tests, I added a few for the defaults... https://github.com/arlimus/inquirer.rb/pull/5

**Comment by blackjid** [comment]
oh!, can you please make a release with this feature??? I want to use it!, :)

**Comment by arlimus** [comment]
Great point! I'll push it a bit later today, I'm currently traveling, won't take too long ;)

**Comment by arlimus** [comment]
Oh and thanks for the added tests! Cheers :)

**Comment by arlimus** [comment]
0.2.1 is online:
https://github.com/arlimus/inquirer.rb/releases
or 
https://rubygems.org/gems/inquirer

Thank you again!

**Comment by blackjid** [comment]
thanks to you!

**Pull request merged**
